export type DemoSite = {
  title: string;
  slug: string;
  tag: string;
  desc: string;
  stack: string;
  demoHref: string;
  liveHref?: string;
  cta: string;
  headline: string;
  audience: string;
  features: string[];
};

export const demoSites: DemoSite[] = [
  { title:"NPSD School ERP", slug:"school-erp", tag:"School SaaS", desc:"Complete school management experience with role-based portals, attendance, results and administration.", stack:"Next.js · Supabase · PostgreSQL · QR", demoHref:"https://student-portal-chi-navy.vercel.app/", liveHref:"https://student-portal-chi-navy.vercel.app/", cta:"Request School ERP", headline:"A smarter operating system for modern schools.", audience:"Schools, academies and education networks", features:["Student portal","Teacher portal","Admin dashboard","Attendance & results"] },
  { title:"University AI Assistant", slug:"university-ai", tag:"AI Web App", desc:"Conversational university assistant for admissions, academics, campus information and student support.", stack:"Next.js · TypeScript · AI", demoHref:"https://aamro-university-agent.vercel.app/", liveHref:"https://aamro-university-agent.vercel.app/", cta:"Build University Assistant", headline:"Give every student an intelligent campus guide.", audience:"Universities and colleges", features:["AI Q&A","University knowledge","Student guidance","Responsive chat UI"] },
  { title:"AI StudyMate", slug:"ai-studymate", tag:"Multi-Agent AI", desc:"Learning platform combining tutoring, quizzes, evaluation, planning and career guidance with RAG.", stack:"Next.js · FastAPI · Supabase · RAG", demoHref:"https://ai-studymate-dkel.vercel.app", liveHref:"https://ai-studymate-dkel.vercel.app", cta:"Build Learning Platform", headline:"An AI learning companion that works around the student.", audience:"Schools, academies and EdTech startups", features:["AI Tutor","Quiz generator","Evaluator","RAG knowledge base"] },
  { title:"Suhail AI", slug:"suhail-ai", tag:"AI Assistant", desc:"Modern personal AI assistant experience with conversational workflows and cloud-backed data.", stack:"React · TypeScript · Supabase · AI", demoHref:"https://personal-ai-assistance-pearl.vercel.app", liveHref:"https://personal-ai-assistance-pearl.vercel.app", cta:"Build AI Assistant", headline:"A private AI workspace for everyday productivity.", audience:"Professionals, teams and founders", features:["AI chat","Task workflows","Cloud data","Modern dashboard"] },
  { title:"Physical AI & Humanoid Robotics", slug:"physical-ai", tag:"AI Documentation", desc:"Interactive technical learning platform for physical AI and humanoid robotics.", stack:"Next.js · TypeScript · Documentation", demoHref:"https://book-skp-claude.vercel.app/", liveHref:"https://book-skp-claude.vercel.app/", cta:"Build Knowledge Platform", headline:"Turn complex technical knowledge into an interactive product.", audience:"Training providers and technical communities", features:["Structured docs","Searchable content","Learning paths","Responsive UI"] },
  { title:"Islamic Worship Assistant", slug:"worship-assistant", tag:"Web Application", desc:"Responsive worship assistant with prayer, Quran and Ramadan-focused experiences.", stack:"Next.js · TypeScript · APIs", demoHref:"https://v0-ramzan-app-features.vercel.app/", liveHref:"https://v0-ramzan-app-features.vercel.app/", cta:"Build Faith App", headline:"Useful digital tools for everyday worship.", audience:"Communities, organizations and app founders", features:["Prayer tools","Quran features","Ramadan tools","Mobile-first UI"] },
  { title:"E-Commerce Book Store", slug:"book-store", tag:"E-Commerce", desc:"Bookstore storefront with catalog, cart, authentication and order workflows.", stack:"Next.js · TypeScript · Sanity", demoHref:"https://final-hackthoon-2-ska-git-main-suhailahmedaamros-projects.vercel.app/", liveHref:"https://final-hackthoon-2-ska-git-main-suhailahmedaamros-projects.vercel.app/", cta:"Build E-Commerce Store", headline:"A conversion-focused storefront built for growth.", audience:"Retailers, publishers and online sellers", features:["Product catalog","Cart & checkout","Orders","Admin-ready architecture"] },
  { title:"NJV School Management", slug:"school-management", tag:"Management System", desc:"School management workflow covering registration, attendance, grades and communication.", stack:"Next.js · TypeScript · Database", demoHref:"https://njv-school.vercel.app/", liveHref:"https://njv-school.vercel.app/", cta:"Build School System", headline:"Bring school operations into one connected workspace.", audience:"Schools and education groups", features:["Registration","Attendance","Grades","Communication"] },
  { title:"GDP Dashboard", slug:"gdp-dashboard", tag:"Data Dashboard", desc:"Interactive economic-data dashboard with country comparisons and historical analytics.", stack:"Python · Streamlit · Pandas · Plotly", demoHref:"https://gdp-dashboard-uskmsgizln.streamlit.app/", liveHref:"https://gdp-dashboard-uskmsgizln.streamlit.app/", cta:"Build Data Dashboard", headline:"Make complex business data easy to understand.", audience:"Organizations, analysts and decision makers", features:["Interactive charts","Comparisons","Trend analysis","Data exploration"] },
  { title:"Multi-Project Python App", slug:"python-suite", tag:"Python Application", desc:"Collection of practical Python utilities and productivity tools in one experience.", stack:"Python · Streamlit · Pandas · Plotly", demoHref:"https://suhailahmedaamro-python-projects-projects-60ybw3.streamlit.app/", liveHref:"https://suhailahmedaamro-python-projects-projects-60ybw3.streamlit.app/", cta:"Build Internal Tool", headline:"Turn repetitive desktop work into a clean web tool.", audience:"Teams with manual workflows", features:["Utility modules","Data tools","Interactive UI","Fast deployment"] },
  { title:"Personal Library Manager", slug:"library-manager", tag:"Web Utility", desc:"Library manager for cataloging books, reading status and collection statistics.", stack:"Python · Streamlit · Pandas", demoHref:"https://suhailahmedaamro-library-manager-py-library-manager-txxaiw.streamlit.app/", liveHref:"https://suhailahmedaamro-library-manager-py-library-manager-txxaiw.streamlit.app/", cta:"Build Management Tool", headline:"A focused digital workspace for organized collections.", audience:"Libraries, schools and private collections", features:["Catalog","Reading status","Statistics","Search"] },
  { title:"Personal Portfolio", slug:"portfolio", tag:"Professional Website", desc:"Responsive professional portfolio with project showcase and contact workflow.", stack:"Next.js · TypeScript · Tailwind", demoHref:"https://suhailahmedaamro.vercel.app/", liveHref:"https://suhailahmedaamro.vercel.app/", cta:"Build Your Portfolio", headline:"Turn your work into a professional digital presence.", audience:"Developers, creators and professionals", features:["Project showcase","Contact workflow","Responsive design","AI assistant"] },
  { title:"AgentForge AI", slug:"agentforge-ai", tag:"Agentic Automation", desc:"Multi-agent workflow concept connecting research, development, review and delivery.", stack:"Python · LangGraph · Agents · MCP", demoHref:"/demos/agentforge-ai", cta:"Build Agent System", headline:"A digital team of specialized AI agents.", audience:"Startups and automation teams", features:["Research agent","Builder agent","Reviewer agent","Workflow orchestration"] },
  { title:"Smart Attendance", slug:"smart-attendance", tag:"Business Automation", desc:"QR-driven attendance workflow designed to replace repetitive manual tracking.", stack:"Web App · QR · Automation", demoHref:"/demos/smart-attendance", cta:"Build Attendance System", headline:"Fast attendance without the paperwork.", audience:"Schools, offices and events", features:["QR check-in","Attendance records","Admin view","Export-ready data"] },
  { title:"Real Estate", slug:"real-estate", tag:"Website Demo", desc:"Premium property marketplace with listings, agents, search and inquiry flows.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/real-estate", cta:"Order Real Estate Website", headline:"Showcase properties with a premium digital experience.", audience:"Real estate agencies and property dealers", features:["Property listings","Advanced search","Agent profiles","Inquiry forms"] },
  { title:"Restaurant", slug:"restaurant", tag:"Website Demo", desc:"Modern restaurant website with menu, reservations, locations and promotional sections.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/restaurant", cta:"Order Restaurant Website", headline:"Make your restaurant look as good online as it does in person.", audience:"Restaurants, cafes and food brands", features:["Digital menu","Reservations","Gallery","Location & contact"] },
  { title:"E-Commerce Store", slug:"ecommerce-store", tag:"Website Demo", desc:"Conversion-focused online store for products, collections, carts and customer journeys.", stack:"Next.js · TypeScript · Payments", demoHref:"/demos/ecommerce-store", cta:"Order E-Commerce Website", headline:"A storefront designed to turn visits into customers.", audience:"Retail and D2C brands", features:["Product pages","Collections","Cart","Checkout-ready UI"] },
  { title:"Hospital & Clinic", slug:"hospital-clinic", tag:"Website Demo", desc:"Professional healthcare website with departments, doctors, services and appointment flows.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/hospital-clinic", cta:"Order Clinic Website", headline:"A trustworthy digital front door for healthcare.", audience:"Hospitals, clinics and medical practices", features:["Doctor profiles","Departments","Appointments","Contact workflows"] },
  { title:"Construction Company", slug:"construction", tag:"Website Demo", desc:"Corporate construction website for projects, services, capabilities and quote requests.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/construction", cta:"Order Construction Website", headline:"Present projects, capability and credibility at a glance.", audience:"Builders and contractors", features:["Project portfolio","Services","Company profile","Quote request"] },
  { title:"Digital Marketing Agency", slug:"digital-marketing", tag:"Website Demo", desc:"High-conversion agency website for services, case studies, process and lead generation.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/digital-marketing", cta:"Order Agency Website", headline:"Turn your marketing expertise into a lead machine.", audience:"Marketing and creative agencies", features:["Services","Case studies","Lead CTA","Process section"] },
  { title:"Software Company", slug:"software-company", tag:"Website Demo", desc:"SaaS and software company website with product messaging, features and conversion paths.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/software-company", cta:"Order Software Website", headline:"Explain complex technology with clarity.", audience:"Software companies and startups", features:["Product overview","Features","Pricing-ready UI","Contact CTA"] },
  { title:"Law Firm", slug:"law-firm", tag:"Website Demo", desc:"Professional legal website with practice areas, attorneys, insights and consultation CTA.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/law-firm", cta:"Order Law Firm Website", headline:"A credible digital presence for a professional legal practice.", audience:"Law firms and legal consultants", features:["Practice areas","Attorney profiles","Insights","Consultation CTA"] },
  { title:"Travel Agency", slug:"travel-agency", tag:"Website Demo", desc:"Travel website for destinations, packages, itineraries and inquiry capture.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/travel-agency", cta:"Order Travel Website", headline:"Turn destinations into bookable experiences.", audience:"Travel agencies and tour operators", features:["Destinations","Packages","Itineraries","Inquiry forms"] },
  { title:"Hotel", slug:"hotel", tag:"Website Demo", desc:"Hospitality website with rooms, amenities, gallery, location and booking-ready flow.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/hotel", cta:"Order Hotel Website", headline:"Give guests a reason to book directly.", audience:"Hotels, resorts and guest houses", features:["Rooms","Amenities","Gallery","Booking CTA"] },
  { title:"Gym & Fitness", slug:"gym", tag:"Website Demo", desc:"Fitness website for memberships, trainers, classes and lead generation.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/gym", cta:"Order Gym Website", headline:"Turn fitness interest into memberships.", audience:"Gyms, studios and trainers", features:["Memberships","Classes","Trainer profiles","Lead forms"] },
  { title:"Salon & Beauty", slug:"salon", tag:"Website Demo", desc:"Elegant salon website for services, stylists, gallery and appointment inquiries.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/salon", cta:"Order Salon Website", headline:"A polished digital experience for your beauty brand.", audience:"Salons, spas and beauty professionals", features:["Services","Stylists","Gallery","Appointment CTA"] },
  { title:"Automobile", slug:"automobile", tag:"Website Demo", desc:"Automotive showroom website with vehicle listings, specifications and inquiry flows.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/automobile", cta:"Order Auto Website", headline:"Put every vehicle detail in front of the buyer.", audience:"Dealers and automotive businesses", features:["Vehicle listings","Specifications","Gallery","Inquiry CTA"] },
  { title:"Furniture", slug:"furniture", tag:"Website Demo", desc:"Premium furniture catalog for collections, products, materials and inquiries.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/furniture", cta:"Order Furniture Website", headline:"Let your products sell through visual storytelling.", audience:"Furniture brands and showrooms", features:["Collections","Product pages","Materials","Inquiry CTA"] },
  { title:"Clothing Brand", slug:"clothing", tag:"Website Demo", desc:"Fashion storefront concept for collections, products, lookbooks and launches.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/clothing", cta:"Order Fashion Website", headline:"Build a fashion brand people remember.", audience:"Clothing brands and boutiques", features:["Collections","Lookbook","Product pages","Launch sections"] },
  { title:"Electronics Store", slug:"electronics", tag:"Website Demo", desc:"Modern electronics storefront with product comparisons, specifications and shopping flows.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/electronics", cta:"Order Electronics Website", headline:"Make technical products easy to compare and buy.", audience:"Electronics retailers and tech brands", features:["Categories","Specifications","Comparison","Shopping UI"] },
  { title:"Education Academy", slug:"education-academy", tag:"Website Demo", desc:"Academy website for courses, instructors, admissions and student inquiries.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/education-academy", cta:"Order Academy Website", headline:"Turn your academy into a digital learning brand.", audience:"Academies and training institutes", features:["Courses","Instructors","Admissions","Student CTA"] },
  { title:"Coaching Business", slug:"coaching", tag:"Website Demo", desc:"Personal coaching website with programs, testimonials, resources and consultation CTA.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/coaching", cta:"Order Coaching Website", headline:"Package your expertise into a professional online presence.", audience:"Coaches, mentors and consultants", features:["Programs","Testimonials","Resources","Booking CTA"] },
  { title:"Events & Conference", slug:"events", tag:"Website Demo", desc:"Event website for schedules, speakers, tickets, sponsors and registration.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/events", cta:"Order Event Website", headline:"Give your next event a digital stage.", audience:"Event organizers and conference teams", features:["Schedule","Speakers","Sponsors","Registration CTA"] },
  { title:"Photography Studio", slug:"photography", tag:"Website Demo", desc:"Visual portfolio website for photographers with galleries, packages and inquiries.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/photography", cta:"Order Photography Website", headline:"Let the work speak through a cinematic portfolio.", audience:"Photographers and creative studios", features:["Galleries","Packages","Portfolio","Inquiry CTA"] },
  { title:"Architecture & Interior", slug:"architecture-interior", tag:"Website Demo", desc:"Premium project showcase for architecture and interior design studios.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/architecture-interior", cta:"Order Architecture Website", headline:"Present spaces, projects and design thinking beautifully.", audience:"Architects and interior studios", features:["Projects","Services","Studio profile","Inquiry CTA"] },
  { title:"NGO & Nonprofit", slug:"ngo", tag:"Website Demo", desc:"Impact-focused nonprofit website for programs, stories, volunteers and donations.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/ngo", cta:"Order NGO Website", headline:"Make your mission easier to discover and support.", audience:"NGOs and community organizations", features:["Programs","Impact stories","Volunteer CTA","Donation-ready UI"] },
  { title:"Logistics Company", slug:"logistics", tag:"Website Demo", desc:"Business website for logistics services, tracking concepts, coverage and quote requests.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/logistics", cta:"Order Logistics Website", headline:"Present your logistics network with clarity.", audience:"Logistics and transport companies", features:["Services","Coverage","Tracking concept","Quote CTA"] },
  { title:"Medical Laboratory", slug:"medical-lab", tag:"Website Demo", desc:"Medical laboratory website for tests, departments, reports and appointment inquiries.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/medical-lab", cta:"Order Lab Website", headline:"Make diagnostic services simple to understand.", audience:"Medical labs and diagnostic centers", features:["Test catalog","Departments","Report concept","Appointment CTA"] },
  { title:"Property Management", slug:"property-management", tag:"Website Demo", desc:"Property management website for listings, services, tenant support and inquiries.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/property-management", cta:"Order Property Website", headline:"Manage and market properties from one polished presence.", audience:"Property managers and real estate operators", features:["Properties","Services","Tenant support","Inquiry CTA"] },
  { title:"Accounting & Consultancy", slug:"accounting-consultancy", tag:"Website Demo", desc:"Professional consultancy website for services, expertise, industries and consultation leads.", stack:"Next.js · TypeScript · Tailwind", demoHref:"/demos/accounting-consultancy", cta:"Order Consultancy Website", headline:"Turn professional expertise into qualified conversations.", audience:"Accountants, consultants and advisory firms", features:["Services","Industries","Expertise","Consultation CTA"] },
  { title:"E-Learning Platform", slug:"elearning", tag:"Website Demo", desc:"Learning platform concept with courses, instructors, progress and student dashboards.", stack:"Next.js · TypeScript · Supabase", demoHref:"/demos/elearning", cta:"Order E-Learning Platform", headline:"Build a learning product around the student journey.", audience:"Course creators and EdTech companies", features:["Course catalog","Learning paths","Instructor profiles","Dashboard concept"] },
  { title:"SaaS / AI Startup", slug:"saas-ai-startup", tag:"Website Demo", desc:"Premium startup landing experience for an AI or SaaS product with clear conversion paths.", stack:"Next.js · TypeScript · Tailwind · AI", demoHref:"/demos/saas-ai-startup", cta:"Order SaaS Website", headline:"Explain your product fast and make the next step obvious.", audience:"AI startups and SaaS founders", features:["Product story","Features","Use cases","CTA sections"] }
];

export function getDemoSite(slug: string) {
  return demoSites.find((site) => site.slug === slug);
}
